### Label , One hot Encoding

In [1]:
### 01. 데이터 준비
import pandas as pd
data = { "eng": ["b", "c", "a", "d"] }
df = pd.DataFrame(data)
print(type(df))
df

<class 'pandas.core.frame.DataFrame'>


eng
0   b
1   c
2   a
3   d

In [2]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

In [3]:
en_x = LabelEncoder()

df["LabelEncoding"] = en_x.fit_transform(df["eng"])

In [4]:
df

eng  LabelEncoding
0   b              1
1   c              2
2   a              0
3   d              3

In [5]:
onehot = OneHotEncoder()
val = df["LabelEncoding"].values.reshape(-1, 1) # OneHotEncoder() # 판다스 -> 원핫 할때 reshape이 필요하다.

y = onehot.fit_transform([df["LabelEncoding"].values] ).toarray() # 값을 변경후, 배열로 만들어준다.
y

array([[1., 1., 1., 1.]])

In [6]:
y = onehot.fit_transform( val ).toarray() # 값을 변경후, 배열로 만들어준다.
y

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [1., 0., 0., 0.],
       [0., 0., 0., 1.]])

In [7]:
onehot_val = pd.DataFrame(y, dtype=int)
print(onehot_val)

df_new = pd.concat([df, onehot_val], axis=1)
df_new

   0  1  2  3
0  0  1  0  0
1  0  0  1  0
2  1  0  0  0
3  0  0  0  1


eng  LabelEncoding  0  1  2  3
0   b              1  0  1  0  0
1   c              2  0  0  1  0
2   a              0  1  0  0  0
3   d              3  0  0  0  1

In [8]:
data = { "회사명": ["MS","Apple", "Google", "Google"]}
df1 = pd.DataFrame(data)
df2 = df1.copy()
df2

회사명
0      MS
1   Apple
2  Google
3  Google

In [9]:
df2["LabelEncoding"] = en_x.fit_transform(df2["회사명"])
df2

회사명  LabelEncoding
0      MS              2
1   Apple              0
2  Google              1
3  Google              1

In [10]:
val2 = df2["LabelEncoding"].values.reshape(-1, 1) 
y2 = onehot.fit_transform( val2 ).toarray() # 값을 변경후, 배열로 만들어준다.
y2

array([[0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.]])

In [11]:
onehot_val2 = pd.DataFrame(y2, dtype=int)

df_new2 = pd.concat([df2, onehot_val2], axis=1)
df_new2

회사명  LabelEncoding  0  1  2
0      MS              2  0  0  1
1   Apple              0  1  0  0
2  Google              1  0  1  0
3  Google              1  0  1  0

In [12]:
titan_tr = pd.read_csv("./train.csv")

In [13]:
titan_tr.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [14]:
titan_tr["SexLB"] = en_x.fit_transform(titan_tr["Sex"])
titan_tr["SexLB"].head()

0    1
1    0
2    0
3    0
4    1
Name: SexLB, dtype: int32

In [15]:
titan_tr["EmbarkedLB"] = en_x.fit_transform(titan_tr["Embarked"])
titan_tr["EmbarkedLB"].head()

0    2
1    0
2    2
3    2
4    2
Name: EmbarkedLB, dtype: int32

In [16]:
val3 = titan_tr["SexLB"].values.reshape(-1, 1) # OneHotEncoder() # 판다스 -> 원핫 할때 reshape이 필요하다.

y3 = onehot.fit_transform( val3 ).toarray() # 값을 변경후, 배열로 만들어준다.

onehot_val3 = pd.DataFrame(y3, dtype=int)

titan_tr = pd.concat([titan_tr, onehot_val3], axis=1)
titan_tr

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  SexLB  EmbarkedLB  0  1  
0        0         A/5 21171   7.2500   NaN        S      1           2  0  1  
1        0          PC 17599  71.2833   C85        C      0           0  1  0  
2        0  STON/O2. 3101282   7.9250   NaN        S      0           2  1  0  
3        0            113803  53.1000  C123        S      0           2  1  0  
4        0            373450   8.0500   NaN        S      1           2  0  1  
..     ...               ...      ...   ...      ...    ...         ... .. ..  
886      0            211536  13.0000   NaN        S      1           2  0  1  
887      0            112053  30.0000   B42        S      0           2  1  0  
888      2        W./C. 6607  23.4500   NaN        S      0           2  1  0  
889      0            111369  30.0000  C148        C      1           0  0  1  
890      0            370376   7.7500   NaN        Q      1           1  0  1  

[891 rows x 16 columns]

In [17]:
### 01. 데이터 준비
import pandas as pd
data = { "feature1":[2,3,8,4],
         "feature2":[22,32,82,42],
         "target": ["b","c", "a", "d"]
       }
df = pd.DataFrame(data)
df

feature1  feature2 target
0         2        22      b
1         3        32      c
2         8        82      a
3         4        42      d

In [18]:
from sklearn import preprocessing

label_encoder = preprocessing.LabelEncoder()
df['lbl_en'] = label_encoder.fit_transform(df['target'])
df

feature1  feature2 target  lbl_en
0         2        22      b       1
1         3        32      c       2
2         8        82      a       0
3         4        42      d       3

In [19]:
train_y = df['lbl_en'].values.reshape(len(df), 1)

onehot_encoder = preprocessing.OneHotEncoder(sparse=False)
train_y_onehot = onehot_encoder.fit_transform(train_y)
print(train_y_onehot)
print(train_y_onehot.shape)

[[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [1. 0. 0. 0.]
 [0. 0. 0. 1.]]
(4, 4)


In [20]:
import pandas as pd
import os

In [21]:
demo_df = pd.DataFrame({"범주형_feature":['양말', '여우', '양말', '상자']})
display(demo_df)

범주형_feature
0          양말
1          여우
2          양말
3          상자

In [22]:
onehot = pd.get_dummies(demo_df)
onehot

범주형_feature_상자  범주형_feature_양말  범주형_feature_여우
0               0               1               0
1               0               0               1
2               0               1               0
3               1               0               0